import Navbar from './components/Navbar'
import './globals.css'
import { Roboto_Serif } from 'next/font/google'

const roboto_serif = Roboto_Serif({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_serif.className}>
        <Navbar/>
        {children}
        {/* <div className="refresh w-14 h-14 rounded-full bg-red-500 absolute bottom-10">

        </div> */}
      </body>
    </html>
  )
}
